### ISSUE TITLE
How I launch only one ball from launch pad

### ISSUE THREAD

**Issue by bha2020** [nayanseth/VR-Cricket#1]
Your code works great but Multiple balls coming from launchpad,so How I launch only one ball from launch pad?
Please help

**Comment by nayanseth** [comment]
@bha2020 The game is very sensitivetothe trigger buttons. Yougot to be careful with the way you press it. Slight press also leads to ball getting launched. One thing that can be done is adding a logic to ignore next few trigger press.

**Comment by bha2020** [comment]
Thank you very much for your reply .I will try that logic.
